In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import seaborn as sns

In [3]:
df = pd.read_csv(r"C:\Users\arsha\Desktop\capstone\dataset_wsn.csv")
df.sample(10)

,Date,Time,epoch,moteid,temperature,humidity,light,voltage
892488,22-03-2004,3:15:58 PM,31480,24,95.4974,43.1858,920.00,2.36622
236777,07-03-2004,3:44:10 PM,24812,7,26.1918,35.6456,264.96,2.65143
437118,08-03-2004,11:22:13 PM,28608,12,21.9484,38.1213,1.38,2.59354
654918,19-03-2004,12:42:19 PM,59008,19,122.1530,23.3435,235.52,2.31097
35663,16-03-2004,11:23:52 PM,51651,1,23.2224,33.0709,43.24,2.48502
364191,12-03-2004,10:04:04 AM,38532,10,21.8602,42.1830,625.60,2.52732
117740,25-03-2004,1:18:34 AM,38445,3,103.2000,42.3170,1.84,2.25825
716059,10-03-2004,3:03:02 AM,31930,21,22.4090,38.5311,3.68,2.57108
781532,12-03-2004,12:14:39 AM,37353,22,21.8602,38.3946,1.84,2.47467
812219,01-03-2004,9:22:52 AM,6770,23,24.8492,33.0709,264.96,2.71196

In [4]:
df.shape

(1048575, 8)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Date         1048575 non-null  object
 1   Time         1048575 non-null  object
 2   epoch        1048575 non-null  int64
 3   moteid       1048575 non-null  int64
 4   temperature  1048440 non-null  float64
 5   humidity     1048440 non-null  float64
 6   light        1025313 non-null  float64
 7   voltage      1048575 non-null  float64
dtypes: float64(4), int64(2), object(2)
memory usage: 64.0+ MB

In [6]:
df.isna().sum()

Date               0
Time               0
epoch              0
moteid             0
temperature      135
humidity         135
light          23262
voltage            0
dtype: int64

In [7]:
df["moteid"].nunique()

27

In [8]:
sorted(df["moteid"].dropna().unique())

[np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9),
 np.int64(10),
 np.int64(11),
 np.int64(12),
 np.int64(13),
 np.int64(14),
 np.int64(15),
 np.int64(16),
 np.int64(17),
 np.int64(18),
 np.int64(19),
 np.int64(20),
 np.int64(21),
 np.int64(22),
 np.int64(23),
 np.int64(24),
 np.int64(25),
 np.int64(26),
 np.int64(27)]

In [9]:
sensor_cols = ["temperature", "humidity", "light", "voltage"]

In [10]:
df[sensor_cols].describe().round(2)

       temperature    humidity       light     voltage
count   1048440.00  1048440.00  1025313.00  1048575.00
mean         40.07       32.57      353.81        2.49
std          38.19       19.01      499.44        0.18
min         -38.40    -8983.13        0.00        0.02
25%          20.58       30.61       30.36        2.39
50%          22.51       38.46      128.80        2.54
75%          27.46       42.85      426.88        2.64
max         122.15      114.89     1847.36        3.16

## Train Test split

performing train test split before doing EDA to prevent data leakage. We don't want test set (which is part of the entire dataset) to influence EDA or any decisions on feature engineering.

In [15]:
df_raw = df.copy()
df_raw["datetime"] = pd.to_datetime(
    df_raw["Date"].astype(str) + " " + df_raw["Time"].astype(str),
    dayfirst=True,
    errors="coerce"
)

df_raw = df_raw.sort_values("datetime").reset_index(drop=True)
split_idx = int(len(df_raw) * 0.75)

df_train = df_raw.iloc[:split_idx].copy()
df_test= df_raw.iloc[split_idx:].copy()

In [16]:
df_train.sample(10)

,Date,Time,epoch,moteid,temperature,humidity,light,voltage,datetime
740249,17-03-2004,9:18:44 PM,54281,3,22.5462,38.9061,39.56,2.47467,2004-03-17 21:18:44
362076,07-03-2004,2:18:37 AM,23201,21,19.9884,43.3858,3.68,2.59354,2004-03-07 02:18:37
321952,06-03-2004,4:59:33 AM,20643,1,19.4494,42.7185,46.92,2.60491,2004-03-06 04:59:33
254245,04-03-2004,4:44:31 PM,16293,7,21.2624,39.0422,128.80,2.63964,2004-03-04 16:44:31
297964,05-03-2004,4:27:34 PM,19139,22,24.6434,35.1609,655.04,2.65143,2004-03-05 16:27:34
617645,13-03-2004,6:53:33 PM,42471,25,23.8202,38.7357,0.46,2.54901,2004-03-13 18:53:33
199127,03-03-2004,10:07:57 AM,12620,18,25.2608,25.6696,507.84,2.50599,2004-03-03 10:07:57
176268,02-03-2004,9:54:29 PM,11153,17,20.9586,28.8661,90.16,2.56000,2004-03-02 21:54:29
606451,13-03-2004,12:16:02 PM,41676,3,27.5932,33.3507,426.88,2.59354,2004-03-13 12:16:02
344147,06-03-2004,4:40:41 PM,22045,3,25.1432,35.5764,202.40,2.66332,2004-03-06 16:40:41

<h3 align="center" style="color:blue">Data Cleaning</h3>

In [17]:
df_train.shape

(786431, 9)

In [18]:
df_train.isna().sum()

Date               0
Time               0
epoch              0
moteid             0
temperature       62
humidity          62
light          16665
voltage            0
datetime           0
dtype: int64