In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import seaborn as sns

In [9]:
df = pd.read_csv(r"C:\Users\arsha\Desktop\capstone\dataset_wsn.csv")
df.sample(10)

,Date,Time,epoch,moteid,temperature,humidity,light,voltage
362178,11-03-2004,2:20:14 PM,36164,10,22.6540,36.0257,507.84,2.51661
663108,29-02-2004,7:26:51 PM,5098,20,19.0084,43.7186,15.64,2.67532
917305,31-03-2004,3:48:48 PM,57467,24,122.1530,-4.0000,713.92,2.14412
89960,21-03-2004,7:04:56 PM,65533,2,21.4290,46.5577,11.04,2.33827
704169,05-03-2004,3:43:32 PM,19051,21,25.1138,34.0487,235.52,2.65143
465767,23-03-2004,10:03:32 AM,33735,13,122.1530,37.5737,1199.68,2.24970
728823,14-03-2004,10:53:04 AM,44390,21,26.5642,33.9093,323.84,2.53812
401230,07-03-2004,12:46:16 PM,24456,11,23.0950,43.1191,1435.20,2.60491
1015908,24-03-2004,4:20:32 AM,35929,26,122.1530,29.2581,1.38,2.25825
918892,19-03-2004,9:40:49 AM,58645,24,23.2126,38.3263,1435.20,2.43410

In [10]:
df.shape

(1048575, 8)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Date         1048575 non-null  object
 1   Time         1048575 non-null  object
 2   epoch        1048575 non-null  int64
 3   moteid       1048575 non-null  int64
 4   temperature  1048440 non-null  float64
 5   humidity     1048440 non-null  float64
 6   light        1025313 non-null  float64
 7   voltage      1048575 non-null  float64
dtypes: float64(4), int64(2), object(2)
memory usage: 64.0+ MB

In [12]:
df.isna().sum()

Date               0
Time               0
epoch              0
moteid             0
temperature      135
humidity         135
light          23262
voltage            0
dtype: int64

In [13]:
df["moteid"].nunique()

27

In [14]:
sorted(df["moteid"].dropna().unique())

[np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9),
 np.int64(10),
 np.int64(11),
 np.int64(12),
 np.int64(13),
 np.int64(14),
 np.int64(15),
 np.int64(16),
 np.int64(17),
 np.int64(18),
 np.int64(19),
 np.int64(20),
 np.int64(21),
 np.int64(22),
 np.int64(23),
 np.int64(24),
 np.int64(25),
 np.int64(26),
 np.int64(27)]

In [15]:
sensor_cols = ["temperature", "humidity", "light", "voltage"]

In [18]:
df[sensor_cols].describe().round(2)

       temperature    humidity       light     voltage
count   1048440.00  1048440.00  1025313.00  1048575.00
mean         40.07       32.57      353.81        2.49
std          38.19       19.01      499.44        0.18
min         -38.40    -8983.13        0.00        0.02
25%          20.58       30.61       30.36        2.39
50%          22.51       38.46      128.80        2.54
75%          27.46       42.85      426.88        2.64
max         122.15      114.89     1847.36        3.16

## Train Test split

performing train test split before doing EDA to prevent data leakage. We don't want test set (which is part of the entire dataset) to influence EDA or any decisions on feature engineering.

In [20]:
df_raw = df.copy()
df_raw["datetime"] = pd.to_datetime(
    df_raw["Date"].astype(str) + " " + df_raw["Time"].astype(str),
    dayfirst=True,
    errors="coerce"
)

df_raw = df_raw.sort_values("datetime").reset_index(drop=True)
split_idx = int(len(df_raw) * 0.75)

df_train_raw = df_raw.iloc[:split_idx].copy()
df_test_raw = df_raw.iloc[split_idx:].copy()

In [22]:
df_train_raw.sample(10)

,Date,Time,epoch,moteid,temperature,humidity,light,voltage,datetime
723544,17-03-2004,11:00:13 AM,53044,13,20.6156,43.5190,1494.08,2.41431,2004-03-17 11:00:13
662430,14-03-2004,9:15:37 PM,45635,19,20.7136,43.8183,43.24,2.46440,2004-03-14 21:15:37
42594,28-02-2004,11:48:50 PM,2742,3,19.5572,38.6675,48.76,2.68742,2004-02-28 23:48:50
164120,02-03-2004,3:26:43 PM,10369,24,28.9554,20.5515,684.48,2.77533,2004-03-02 15:26:43
307085,05-03-2004,9:16:07 PM,19716,7,21.0272,41.0404,101.20,2.62796,2004-03-05 21:16:07
161028,02-03-2004,1:42:47 PM,10168,12,22.7128,28.7591,1847.36,2.67532,2004-03-02 13:42:47
258187,04-03-2004,6:47:00 PM,16538,9,20.9488,40.4666,97.52,2.71196,2004-03-04 18:47:00
36291,28-02-2004,8:32:18 PM,2349,25,20.3510,39.6200,97.52,2.69964,2004-02-28 20:32:18
500228,10-03-2004,12:21:37 AM,31607,26,22.7030,43.5855,114.08,2.59354,2004-03-10 00:21:37
390500,07-03-2004,5:25:39 PM,25015,17,25.4176,36.8527,323.84,2.54901,2004-03-07 17:25:39

In [ ]:
<h3 align="center" style="color:blue">Data Cleaning</h3>